# Generated by Django 3.0.5 on 2020-05-28 13:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='', max_length=200)),
                ('house_rules', models.BooleanField(default=False)),
                ('num_rounds', models.IntegerField(default=3)),
                ('round', models.IntegerField(default=0)),
                ('stage', models.IntegerField(choices=[(0, 'Gathering'), (1, 'Playing'), (2, 'Round Over'), (3, 'Game Over')], default=0)),
                ('next_player', models.IntegerField(default=-1)),
                ('deck', models.CharField(default='', max_length=100)),
                ('pool', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('cash', models.PositiveSmallIntegerField(default=11)),
                ('hand', models.CharField(default='', max_length=100)),
                ('turn_order', models.IntegerField(default=-1)),
                ('owner', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nothanks.Game')),
            ],
        ),
    ]
