# Generated by Django 3.0.5 on 2020-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nothanks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='cash',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='player',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
