# Generated by Django 3.0.5 on 2020-05-06 15:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='', max_length=200)),
                ('stage', models.IntegerField(choices=[(0, 'Gathering'), (1, 'Starting'), (2, 'Placing'), (3, 'Bidding'), (4, 'Flipping'), (5, 'Flipper Lost'), (6, 'Flipper Won'), (7, 'Over')], default=0)),
                ('next_player', models.IntegerField(default=-1)),
                ('placed', models.IntegerField(default=0)),
                ('bidder', models.IntegerField(default=-1)),
                ('bid', models.IntegerField(default=0)),
                ('flipped', models.IntegerField(default=0)),
                ('skuller', models.IntegerField(default=-1)),
                ('winner', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('alive', models.BooleanField(default=True)),
                ('passed', models.BooleanField(default=False)),
                ('hand', models.CharField(default='0001', max_length=4)),
                ('stack', models.CharField(default='', max_length=4)),
                ('flipped', models.IntegerField(default=0)),
                ('turn_order', models.IntegerField(default=-1)),
                ('owner', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skull.Game')),
            ],
        ),
    ]
