# Generated by Django 3.0.5 on 2020-06-26 14:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('tag', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='', max_length=200)),
                ('stage', models.IntegerField(choices=[(0, 'Gathering'), (1, 'Starting'), (2, 'Playing'), (3, 'Game Over')], default=0)),
                ('next_player', models.IntegerField(default=-1)),
                ('card', models.IntegerField(default=-1)),
                ('house_rules', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('hand', models.CharField(default='', max_length=100)),
                ('tricks', models.CharField(default='', max_length=100)),
                ('turn_order', models.IntegerField(default=-1)),
                ('owner', models.BooleanField(default=False)),
                ('seen', models.BooleanField(default=False)),
                ('claim', models.IntegerField(default=-1)),
                ('target', models.IntegerField(default=-1)),
                ('nominator', models.IntegerField(default=-1)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Playing'), (2, 'Watching'), (3, 'Lost'), (4, 'Won')], default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cockroach.Game')),
            ],
        ),
    ]
